#!/bin/bash
# DIAB Healthcheck Script
#
HealthCheck=0
if [ $DIAB_HEALTHCHECK_SCRIPT ]; then
        /usr/sbin/diab_health_json
        HealthCheck=$?
else
        /usr/sbin/diab_health_script
        HealthCheck=$?
fi
exit $HealthCheck
