#!/bin/bash
# DIAB Startup Script
DV=`cat /etc/dnsdist/diab_version.txt`
echo "#"
echo "# DIAB : INFO    : Attempting to start diab V$DV..."
# Run the configurator....
echo "# DIAB : INFO    : Launching diab V$DV configurator..."
# Check for override...
if [ $DIAB_FORCEREBUILD ]; then
	if [ $DIAB_FORCEREBUILD -eq 1 ]; then
		/usr/sbin/diab_confbuild OVERRIDE
	else
		/usr/sbin/diab_confbuild
	fi
else
	/usr/sbin/diab_confbuild
fi
# Check for/enable advanced logging
if [ $DIAB_ENABLE_ADVANCED_LOGGING ]; then
        if [ $DIAB_ENABLE_ADVANCED_LOGGING -eq 1 ]; then
                echo "# DIAB : INFO    : Advanced logging requested..."
                advlog="-v"
        else
                advlog=""
        fi
fi
# Start dnsdist...
echo "# DIAB : INFO    : Launching dnsdist..."
dnscrypt-proxy --config /etc/dnscrypt/dnscrypt-proxy.toml &
dnsdist -C /etc/dnsdist/dnsdist.conf --supervised $advlog

